name: 构建和发布 EXE

on:
  push:
    tags:
      - 'v*'  # 当推送标签匹配 v* 时运行工作流，例如 v1.0, v2.3.1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 使用 PyInstaller 构建 EXE
        run: |
          pyinstaller --onefile --windowed --icon=1.webp --name=MarkdownSummarizer 1.py

      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: 发布 ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/MarkdownSummarizer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}